kustomize build kubeflow-manifests/common/cert-manager/base > ./0kubeflow/cert-manager.yaml
kustomize build kubeflow-manifests/common/cert-manager/kubeflow-issuer/base > ./0kubeflow/kubeflow-issuer.yaml
kustomize build kubeflow-manifests/common/istio-1-23/istio-crds/base > ./0kubeflow/istio-crds.yaml
kustomize build kubeflow-manifests/common/istio-1-23/istio-namespace/base > ./0kubeflow/istio-namespace.yaml
kustomize build kubeflow-manifests/common/istio-1-23/istio-install/overlays/oauth2-proxy > ./0kubeflow/istio-install.yaml
kustomize build kubeflow-manifests/common/oauth2-proxy/overlays/m2m-dex-only/ > ./0kubeflow/oauth2-proxy.yaml
kustomize build kubeflow-manifests/common/dex/overlays/oauth2-proxy > ./0kubeflow/dex.yaml
kustomize build kubeflow-manifests/common/knative/knative-serving/overlays/gateways > ./0kubeflow/knative-serving.yaml
kustomize build kubeflow-manifests/common/istio-1-23/cluster-local-gateway/base > ./0kubeflow/cluster-local-gateway.yaml
kustomize build kubeflow-manifests/common/kubeflow-namespace/base > ./0kubeflow/kubeflow-namespace.yaml
kustomize build kubeflow-manifests/common/networkpolicies/base > ./0kubeflow/networkpolicies.yaml
kustomize build kubeflow-manifests/common/kubeflow-roles/base > ./0kubeflow/kubeflow-roles.yaml
kustomize build kubeflow-manifests/common/istio-1-23/kubeflow-istio-resources/base > ./0kubeflow/kubeflow-istio-resources.yaml
kustomize build kubeflow-manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user > ./0kubeflow/multi-user.yaml
kustomize build kubeflow-manifests/contrib/kserve/kserve > ./0kubeflow/kserve.yaml
kustomize build kubeflow-manifests/contrib/kserve/models-web-app/overlays/kubeflow > ./0kubeflow/kserve-ui.yaml
kustomize build kubeflow-manifests/apps/katib/upstream/installs/katib-with-kubeflow > ./0kubeflow/katib.yaml
kustomize build kubeflow-manifests/apps/centraldashboard/overlays/oauth2-proxy > ./0kubeflow/centraldashboard.yaml
kustomize build kubeflow-manifests/apps/admission-webhook/upstream/overlays/cert-manager > ./0kubeflow/admission-webhook.yaml
kustomize build kubeflow-manifests/apps/jupyter/notebook-controller/upstream/overlays/kubeflow > ./0kubeflow/notebook-controller.yaml
kustomize build kubeflow-manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio > ./0kubeflow/jupyter-web-app.yaml
kustomize build kubeflow-manifests/apps/pvcviewer-controller/upstream/default > ./0kubeflow/pvcviewer-controller.yaml
kustomize build kubeflow-manifests/apps/profiles/upstream/overlays/kubeflow > ./0kubeflow/profiles.yaml
kustomize build kubeflow-manifests/apps/volumes-web-app/upstream/overlays/istio > ./0kubeflow/volumes-web-app.yaml
kustomize build kubeflow-manifests/apps/tensorboard/tensorboards-web-app/upstream/overlays/istio > ./0kubeflow/tensorboards-web-app.yaml
kustomize build kubeflow-manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow > ./0kubeflow/tensorboard-controller.yaml
kustomize build kubeflow-manifests/apps/training-operator/upstream/overlays/kubeflow > ./0kubeflow/training-operator.yaml
kustomize build kubeflow-manifests/common/user-namespace/base > ./0kubeflow/user-namespace.yaml